apiVersion: batch/v1
kind: Job
spec:
  backoffLimit: 0
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      restartPolicy: Never

      containers:
        - name: app
          image: localhost:32000/jenkins/python-ci:3.12
          command: ["python", "-m", "src.app"]
          args: ["3", "5"]
