apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: localhost:32000/jenkins/python-ci:3.12
      imagePullPolicy: IfNotPresent
      command: ["cat"]
      tty: true

    - name: terraform
      image: hashicorp/terraform:1.6
      command: ["cat"]
      tty: true

    - name: security-tools
      image: bridgecrew/checkov:latest
      command: ["cat"]
      tty: true

    - name: deploy-tools
      image: bitnami/helm:3.14
      command: ["cat"]
      tty: true