apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    
  containers:
    - name: deploy-tools
      image: alpine/helm:4
      command: ["cat"]
      tty: true
