apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-deploy
spec:
  containers:
    - name: dind
      image: docker:26-dind
      securityContext:
        privileged: true         # DinD requires privileged container
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""             # disable TLS for simplicity in local cluster
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
