apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  containers:
    - name: deploy-container
      image: "${IMAGE_NAME}:${BUILD_NUMBER}-patched"  # Placeholder for dynamic image name
      imagePullPolicy: IfNotPresent
      command: ["cat"]
      tty: true
