apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  hostNetwork: true  # Allow the pod to use the host network
  containers:
    - name: dind
      image: docker:latest
      securityContext:
        privileged: true  # Required for DinD
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
