apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  containers:
    - name: deploy-container
      image: localhost:32000/jenkins/python-ci:3.12  # Hardcoded image name
      imagePullPolicy: IfNotPresent
      command: ["cat"]
      tty: true
