apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-deploy
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
    - name: dind
      image: docker:26-dind
      securityContext:
        runAsUser: 1000       # Jenkins user inside the container
        fsGroup: 1000         # group for mounted volumes
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - name: workspace
      emptyDir: {}
