apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  containers:
    - name: terraform
      image: hashicorp/terraform:1.6
      command: ["cat"]
      tty: true
